# Generated by Django 6.0.3 on 2026-04-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
